#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

IMAGE=${REPO}/tke-operator:${TAG}
DOCKERFILE=package/Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

docker build -f ${DOCKERFILE} -t ${IMAGE} .
echo ${REPO}/tke-operator:${VERSION} > dist/images.txt

echo Built ${IMAGE}